export const METRICS = {
    accPp: 'accPp',
    passPp: 'passPp',
    techPp: 'techPp',
    sspPlays: 'sspPlays',
    ssPlays: 'ssPlays',
    spPlays: 'spPlays',
    sPlays: 'sPlays',
    aPlays: 'aPlays',
    totalScore: 'Total score',
    totalUnrankedScore: 'Total unranked score',
    totalRankedScore: 'Total ranked score',
    lastScoreTime: 'Last score time',
    lastUnrankedScoreTime: 'Last unranked score time',
    lastRankedScoreTime: 'Last ranked score time',
    averageRankedAccuracy: 'Average ranked accuracy',
    averageWeightedRankedAccuracy: 'average Weighted Ranked Accuracy',
    averageUnrankedAccuracy: 'average Unranked Accuracy',
    averageAccuracy: 'averageAccuracy',
    medianRankedAccuracy: 'medianRankedAccuracy',
    medianAccuracy: 'median Ranked Accuracy',
    topRankedAccuracy: 'top Ranked Accuracy',
    topUnrankedAccuracy: 'top Unranked Accuracy',
    topAccuracy: 'topAccuracy',
    topPp: 'topPp',
    topBonusPP: 'topBonusPP',
    topPassPP: 'topPassPP',
    topAccPP: 'topAccPP',
    topTechPP: 'topTechPP',
    peakRank: 'peakRank',
    rankedMaxStreak: 'ranked Max Streak',
    unrankedMaxStreak: 'unranked Max Streak',
    maxStreak: 'maxStreak',
    averageLeftTiming: 'average Left Timing',
    averageRightTiming: 'averageRightTiming',
    rankedPlayCount: 'ranked Play Count',
    unrankedPlayCount: 'unranked Play Count',
    totalPlayCount: 'total Play Count',
    rankedImprovementsCount: 'ranked Improvements Count',
    unrankedImprovementsCount: 'unranked Improvements Count',
    totalImprovementsCount: 'total Improvements Count',
    rankedTop1Score: 'ranked Top 1 Score',
    unrankedTop1Score: 'unranked Top 1 Score',
    top1Score: 'top 1 Score',
    averageRankedRank: 'average Ranked Rank',
    averageWeightedRankedRank: 'average Weighted Ranked Rank',
    averageUnrankedRank: 'average Unranked Rank',
    averageRank: 'average Rank',
    topPlatform: 'topPlatform',
    topHMD: 'topHMD',
    topPercentile: 'topHMD',
    countryTopPercentile: 'countryTopPercentile',
    dailyImprovements: 'daily Improvements',
    watchedReplays: 'watched Replays',
    lastWeekPp: 'last Week Pp',
    lastWeekRank: 'last Week Rank',
    lastWeekCountryRank: 'last Week Country Rank',
    replaysWatched: 'replays Watched'
}